language: ruby
rvm:
  - 2.1.0
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database gitcycle_api2_test;' -U postgres
addons:
  code_climate:
    repo_token: dfb262648d047dc914dc9438428fc109f1dc7e029fe5fb123f3759997ec10442